package com.example.sandbox.constants;

/**
 * Collected constants of HTML utility. All members of this class are immutable.
 */
public final class MarkupConstants {

    public static final String RESET_PASSWORD_EMAIL_PART_1 = "<body style=\"margin:0\"><div style=\"background:#f2f2f2; margin:0 auto; max-width:640px; padding:0 20px;\"><table style=\"position:relative;\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\"><tbody><tr><td><div style=\"background:#fff; color:#5B5B5B; border-radius:4px; box-shadow:0px 1px 0px #ccc; font-family:arial; font-size:13px; padding:10px 20px; width:90%; margin:20px auto; line-height:17px; border:1px #ddd solid; clear:both\"><p>Hi there !</p><p> Somebody recently asked to reset your Sandbox Dropwizard account password.</p><p> <a href=\"";

    public static final String RESET_PASSWORD_EMAIL_PART_2 = "\" target=\"_blank\" style=\"font-size:13px;color:#00baf0;text-decoration:none\">Click here</a> to reset your  password.</p><p>If  you did not request a new password, please let us know immediately at <a href=\"mailto:support@example.com\" target=\"_blank\" style=\"font-size:13px;color:#00baf0;text-decoration:none\">support@example.com</a></p><p>See you soon on Sandbox Dropwizard.</p><p>Sandbox Dropwizard Support Team</p></div></td></tr></tbody></table></div></body>";

    public static final String RESET_PASSWORD_PART_1 = "<!doctype html><html><head><meta charset=\"utf-8\"><meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"><meta name=\"description\" content=\"\"><meta name=\"author\" content=\"\"><title>Sandbox Dropwizard - Reset Password</title><link href=\"lib/bootstrap/css/bootstrap.css\" type=\"text/css\" rel=\"stylesheet\"><!-- Bootstrap Core CSS --><link href=\"lib/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\"><!-- Bootstrap Override CSS --><link href=\"css/bootstrap_override.css\" rel=\"stylesheet\"><!-- Custom CSS --><link href=\"lib/simple-sidebar/css/simple_sidebar.css\" rel=\"stylesheet\"><!-- Custom Fonts --><link href=\"lib/font-awesome/css/font-awesome.min.css\" rel=\"stylesheet\" type=\"text/css\"><!--jquery validator--><link rel=\"stylesheet\" href=\"http://jqueryvalidation.org/files/demo/site-demos.css\"><script type=\"text/javascript\" src=\"lib/bootstrap/js/bootstrap.min.js\"></script><!--<script src=\"lib/jquery.js\"></script><script src=\"lib/jquery.validate.js\"></script>--></head><body><nav class=\"navbar navbar-inverse navbar-fixed-top\"><div class=\"container-fluid\"><!-- Brand and toggle get grouped for better mobile display --><div class=\"navbar-header\"><a class=\"navbar-brand\">Sandbox Dropwizard</a></div></div><!-- /.container-fluid --></nav><div class=\"whitespace\" style=\"margin-top: 50px\"></div><!-- Page Content --><div id=\"page-content-wrapper\"><div class=\"container-fluid\"><div class=\"col-xs-12\"><div class=\"password-reset-form\"><form id=\"myform\" method=\"post\" action=\"/api/reset-password?token=";

    public static final String RESET_PASSWORD_PART_2 = "\"><div class=\"row\"><label>Email</label><input class=\"form-control\" type=\"text\" name=\"email\" ></div><div class=\"row\"><label>Password</label><input class=\"form-control\" type=\"password\" id=\"password\" name=\"password\"></div><div class=\"row\"><label>Confirm Password</label><input class=\"form-control\" type=\"password\" id=\"password_again\" name=\"password_again\" ></div><div class=\"row\"><input class=\"form-control\" type=\"submit\" name=\"Reset\"></div></form></div></div></div></div><!-- /#page-content-wrapper --><!-- jQuery --><script src=\"lib/bootstrap/js/jquery.js\"></script><!-- Bootstrap Core JavaScript --><script src=\"lib/bootstrap/js/bootstrap.min.js\"></script><script src=\"http://code.jquery.com/jquery-1.11.1.min.js\"></script><script src=\"http://jqueryvalidation.org/files/assets/jquery.validate.min.js\"></script><script src=\"http://jqueryvalidation.org/files/assets/additional-methods.min.js\"></script><script>$( \"#myform\" ).validate({rules: {email: {required: true,email: true},password: \"required\",password_again: {equalTo: \"#password\"}}});$(\"#myform\").validate({success: \"valid\",submitHandler: function() { $( \"#myform\").submit(); }});</script><nav class=\"navbar navbar-inverse navbar-fixed-bottom\"><div class=\"container-fluid\"></div></nav></body></html>";

    public static final String RESET_PASSWORD_SUCCESS = "<!DOCTYPE html><html><head lang=\"en\"><meta charset=\"UTF-8\"><title>Password Reset Success</title><link href=\"lib/bootstrap/css/bootstrap.css\" type=\"text/css\" rel=\"stylesheet\"><script type=\"text/javascript\" src=\"lib/bootstrap/js/jquery.js\"></script><script type=\"text/javascript\" src=\"lib/bootstrap/js/bootstrap.min.js\"></script><link href='http://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'><link rel=\"stylesheet\" href=\"lib/simple-sidebar/css/landing_page.css\"></head><body><div class=\"container-fluid screenMask\"><h1 class=\"text-center textCongratulation\">CONGRATULATION</h1><p class=\"text-center passwordReset\">Your password for Sandbox Dropwizard has been reset,please continue and try your new password at Sandbox Dropwizard</p><p class=\"text-center copyRights\">Copyright &copy; 2015 | All Rights Reserved</p></div></body></html>";

}
